point_cloud_topic: "/point_cloud_filter/rslidar/point_cloud"
map_frame_id: "odom"
robot_base_frame_id: "base"
robot_pose_with_covariance_topic: '/state_estimator/pose_in_odom'
robot_pose_cache_size: 200
track_point_frame_id: "base"
track_point_x: 0.0
track_point_y: 0.0
track_point_z: 0.0
